; ========================================================
; Asterisk Music on Hold Configuration (MOH)
; Clases de musica en espera personalizadas por entidad
; ========================================================
[general]

[default]
mode=files
directory=/var/lib/asterisk/sounds/custom
sort=alpha

[moh_bank]
mode=files
directory=/var/lib/asterisk/sounds/custom
sort=alpha

[moh_corporate]
mode=files
directory=/var/lib/asterisk/sounds/custom
sort=alpha

[moh_digital]
mode=files
directory=/var/lib/asterisk/sounds/custom
sort=alpha
