; ========================================================
; GENERADO AUTOMATICAMENTE POR ANONYMOUS OTP SYSTEM
; Fecha: 2026-09-18T13:52:40.553Z
; Total Extensiones: 1
; Asterisk 20 Validated: No Duplicate Section Headers
; ========================================================

[general]

; --- TRANSPORTES SIP ---
[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060

[transport-tcp]
type = transport
protocol = tcp
bind = 0.0.0.0:5060

[transport-wss]
type = transport
protocol = wss
bind = 0.0.0.0:8089

; --- EXTENSIÓN undefined (Agente) ---
[undefined]
type = endpoint
context = from-internal
disallow = all
allow = ulaw,alaw,g722
auth = undefined-auth
aors = undefined,undefined-aor
callerid = "Seguridad Bancaria" <+18005550199>
direct_media = no
rtp_symmetric = yes
force_rport = yes
rewrite_contact = yes
send_pai = yes
send_rpid = yes
trust_id_outbound = yes
trust_id_inbound = yes
callerid_privacy = allowed
transport = transport-udp

[undefined-auth]
type = auth
auth_type = userpass
username = undefined
password = Robert2026RDTGcvgbsg

[undefined]
type = aor
max_contacts = 5
remove_existing = yes
qualify_frequency = 60
qualify_timeout = 3.0

[undefined-aor]
type = aor
max_contacts = 5
remove_existing = yes
qualify_frequency = 60
qualify_timeout = 3.0

; ========================================================
; TRONCALES / CARRIERS SIP (OUTBOUND & INBOUND)
; ========================================================

; --- CARRIER: ghost (ghostcall.online:5060) ---
[ghost_aor]
type = aor
contact = sip:ghostcall.online:5060
qualify_frequency = 60

[ghost]
type = endpoint
context = trunkinbound
disallow = all
allow = ulaw,alaw,g729
aors = ghost_aor
callerid = "Seguridad Bancaria" <+18005550199>
from_user = sgavilan30
from_domain = ghostcall.online
contact_user = sgavilan30
direct_media = no
rtp_symmetric = yes
force_rport = yes
rewrite_contact = yes
send_pai = yes
send_rpid = yes
trust_id_outbound = yes
trust_id_inbound = yes
callerid_privacy = allowed
transport = transport-udp

[ghost-identify]
type = identify
endpoint = ghost
match = ghostcall.online

